name: Docker Development Deploy

on:
  push:
    branches: [ development ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3      
    - name: Docker-Compose Remote Deployment
      uses: TapTap21/docker-remote-deployment-action@v1.1
      with:
        remote_docker_host: docker-deploy@brinks-ict.nl
        ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
        stack_file_name: 01-Website/docker-compose.yml
        args: up --build -d

